---
apiVersion: v2
appVersion: 1.32.3
description: Vaultwarden is a Bitwarden compatable server in Rust
name: vaultwarden
version: 6.10.0
kubeVersion: ">=1.16.0-0"
keywords:
  - Vaultwarden
  - Bitwarden
  - bitwardenrs
home: https://github.com/andrenarchy/helm-charts/tree/main/charts/vaultwarden
icon: https://lab.uberspace.de/_images/vaultwarden.png
sources:
  - https://github.com/dani-garcia/vaultwarden
maintainers:
  - name: André Gaul
    email: andre@gaul.io
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
  - name: mariadb
    version: 11.0.14
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
  - name: postgresql
    version: 11.6.12
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
