---
apiVersion: v2
appVersion: 1.30.1
description: Vaultwarden is a Bitwarden compatable server in Rust
name: vaultwarden
version: 6.0.1
kubeVersion: ">=1.16.0-0"
keywords:
  - Vaultwarden
  - bitwardenrs
home: "https://github.com/k8s-at-home/charts/tree/master/charts/stable/vaultwarden"
icon: "https://sesoodan.sirv.com/bitwarden_rs.png"
sources:
  - https://github.com/dani-garcia/vaultwarden
maintainers:
  - name: André Gaul
    email: andre@gaul.io
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
  - name: mariadb
    version: 11.0.14
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
  - name: postgresql
    version: 11.6.12
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.5.2
